In [1]:
import numpy as np

# Sales Data Analysis

## Project Overview

This project focuses on analyzing sales data.

The dataset contains sales information for different products
across different months. The analysis helps in understanding
sales trends, product performance, and overall business performance.

## Objectives

- Analyze sales data
- Calculate total and average sales
- Find highest and lowest sales
- Perform monthly sales analysis
- Perform product-wise sales analysis
- Identify the top-performing product
- Analyze overall sales performance

In [2]:
months = np.array([
    "January", "February", "March", "April", "May", "June",
"July", "August", "September", "October", "November", "December"
])


products = np.array([
    "Laptop", "Smartphone", "Headphones", "Keyboard", "Mouse"
])

sales = np.array([
    [45000,38000,12000,8000,5000], 
    [43500,40500,11800,8700,5300], 
    [48200,39500,13200,8400,5800], 
    [46100,42500,12600,9100,5600], 
    [51500,44800,13900,9300,6200], 
    [53200,47200,15100,9800,6800], 
    [49800,45900,14500,9200,6400],
    [55600,48500,15800,10100,7100], 
    [54100,51200,16200,10500,7300], 
    [62800,58400,18100,11900,8200], 
    [71400,65200,20900,13400,9100],
    [79200,73800,23600,15100,10200]
])

In [3]:
sales.shape

(12, 5)

In [4]:
sales.size

60

## Dataset Description
The dataset contains monthly sales data for five products from January to December.

In [5]:
## Q-1: Calculate Total Sales

In [6]:
total_sales = np.sum(sales)
total_sales

np.int64(1650100)

In [7]:
## Q-2: Calculate Average Sales

In [8]:
average_sales = np.average(sales)
average_sales

np.float64(27501.666666666668)

In [9]:
## Q-3: Find the Highest Individual Sale

In [10]:
highest_sales = np.max(sales)
highest_index = np.argmax(sales)
row, column = np.unravel_index(np.argmax(sales), sales.shape)
months[row], products[column], sales[row, column]

(np.str_('December'), np.str_('Laptop'), np.int64(79200))

In [11]:
## Q-4: Find the Lowest Individual Sale

In [12]:
lowest_sales = np.min(sales)
lowest_index = np.argmin(sales)
row, column = np.unravel_index(np.argmin(sales), sales.shape)
months[row], products[column], sales[row, column]

(np.str_('January'), np.str_('Mouse'), np.int64(5000))

In [13]:
## Q-5: Calculate Total Sales for Each Month

In [14]:
month_total_sales = np.sum(sales,axis=1)
month_total_sales

array([108000, 109800, 115100, 115900, 125700, 132100, 125800, 137100,
       139300, 159400, 180000, 201900])

In [15]:
## Q-6: Find the Highest-Selling Month

In [16]:
highest_month_index = np.argmax(month_total_sales)
months[highest_month_index]

np.str_('December')

In [17]:
## Q-7: Find the Lowest-Selling Month

In [18]:
lowest_month_index = np.argmin(month_total_sales)
months[lowest_month_index]

np.str_('January')

In [19]:
## Q-8: Calculate Total Sales for Each Product

In [20]:
productwise_total_sales = np.sum(sales,axis=0)
productwise_total_sales

array([660400, 595500, 187700, 123500,  83000])

In [21]:
## Q-9: Find the Highest-Performing Product

In [22]:
highest_product_index = np.argmax(productwise_total_sales)
products[highest_product_index]

np.str_('Laptop')

In [23]:
## Q-10: Find the Lowest-Performing Product

In [24]:
lowest_product_index = np.argmin(productwise_total_sales)
products[lowest_product_index]

np.str_('Mouse')

In [25]:
## Q-11: Calculate Average Sales for Each Product

In [26]:
product_average_sales = np.average(sales,axis=0)
product_average_sales

array([55033.33333333, 49625.        , 15641.66666667, 10291.66666667,
        6916.66666667])

In [27]:
## Q-12: Calculate Average Sales for Each Month

In [28]:
monthly_average_sales = np.average(sales,axis=1)
monthly_average_sales

array([21600., 21960., 23020., 23180., 25140., 26420., 25160., 27420.,
       27860., 31880., 36000., 40380.])

In [29]:
## Q-13: Find the Month with the Highest Average Sales

In [30]:
monthly_highest_average_sales_index = np.argmax(monthly_average_sales)
months[monthly_highest_average_sales_index]

np.str_('December')

In [31]:
## Q-14: Find the Month with the Lowest Average Sales

In [32]:
monthly_lowest_average_sales_index = np.argmin(monthly_average_sales)
months[monthly_lowest_average_sales_index]

np.str_('January')

In [33]:
## Q-15: Find the Difference Between Highest and Lowest Monthly Sales

In [34]:
highest_monthly_sales = np.max(month_total_sales)
lowest_monthly_sales = np.min(month_total_sales)
difference = highest_monthly_sales - lowest_monthly_sales
difference

np.int64(93900)

In [35]:
## Q-16: Find the Month with the Largest Month-over-Month Sales Increase

In [42]:
monthly_sales_difference = np.diff(month_total_sales)
highest_increase_index = np.argmax(monthly_sales_difference)
months[highest_increase_index + 1]

np.str_('December')

In [43]:
## Q-17: Find the Product with the Highest Average Sales

In [44]:
product_highest_average_sales_index = np.argmax(product_average_sales)
products[product_highest_average_sales_index]

np.str_('Laptop')

In [45]:
## Q-18: Find the Product with the Lowest Average Sales

In [46]:
product_lowest_average_sales = np.argmin(product_average_sales)
products[product_lowest_average_sales]

np.str_('Mouse')

In [47]:
## Q-19: Find the Product with the Largest Sales Growth

In [48]:
product_sales_growth = sales[11] - sales[0]
product_sales_growth

array([34200, 35800, 11600,  7100,  5200])

In [49]:
highest_growth_index = np.argmax(product_sales_growth)
products[highest_growth_index]

np.str_('Smartphone')

In [50]:
## Q-20: Find the Product with the Highest Sales Contribution (%)

In [51]:
product_contribution = (productwise_total_sales / np.sum(sales)) * 100
highest_contribution_index = np.argmax(product_contribution)
products[highest_contribution_index]
product_contribution[highest_contribution_index]

np.float64(40.02181685958427)

In [52]:
products[highest_contribution_index]

np.str_('Laptop')

## Key Insights

The analysis identifies the highest and lowest performing
products, monthly sales trends, sales growth, and product
contribution to overall sales.

## Conclusion

This project demonstrates the use of NumPy for analyzing
sales data and extracting meaningful business insights.